### ISSUE TITLE
Accepted Price Range

### ISSUE THREAD

**Issue by athib2** [alletsee/pricesensitivitymeter#10]
In this package, the PMC and PME are found at the intersection of the "too cheap" and "expensive" lines and the "too expensive" and "cheap" lines. However, for this method, the "expensive" and "cheap" lines need to be inverted so that "expensive" becomes "NOT expensive" and "cheap" becomes "NOT a good value." The intersection of "not a good value" and "too cheap" yields the PMC and the intersection of "not getting expensive" and "too expensive" yields the PME. Is there any way that this could be implemented into the code?

Here is a link to van Westendorp's original article stating how everything is calculated: https://rwconnect.esomar.org/a-new-approach-to-study-consumer-perception-of-price/

Thank you for your time!

**Comment by alletsee** [comment]
Thank you for raising the issue. I had a quick look just now and think that you have a point. I wrote the original code with the original paper next to me, but I agree with you that not all inversions of the cumulative density function have been carried out properly. Thanks for pointing this out.
The suggestion can definitely be implemented in the code. I might need a bit of time on the next weekend(s), though...

**Comment by athib2** [comment]
Excellent, thanks for taking this on! Looking forward to seeing how it turns out.

**Comment by alletsee** [comment]
Thanks again for your comment. I had some time to look into it and can confirm that you are right.
I have just pushed the update to this Github repository and will send it to CRAN in the next couple of minutes. If you want to use it right away, you can install the package directly from Github by using the following code: 
`library(devtools`
`install_github("alletsee/pricesensitivitymeter")`

If you have a bit of time and a data set at hand, it would be amazing if you could try out the new version and let me know if you can see that the correction is working. Thanks again for flagging it!

**Comment by athib2** [comment]
The correction works perfectly! Thank you for taking the time to make those changes. My only other suggestion comes from the 'visualizing psm results' vignette. When annotating the IDP on the plot (lines 208-218), the code uses ecdf_not_cheap instead of ecdf_cheap, leading to incorrect placement of the label. Everything else looks great.

**Comment by alletsee** [comment]
Thanks, you are completely right. I just fixed this in the vignette - when you reinstall the package from Github via devtools, it should be fixed.
I decided to not push this single change into the CRAN version, as the point is not terribly off in the plot and I am working on additional functionality for the package.

**Comment by athib2** [comment]
Thank you so much for making these changes. Excited to see what the additional functionality is!
